version: "2"

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - bodyclose
    - gosec

  settings:
    revive:
      confidence: 0.8
    gosec:
      excludes:
        - G404
    errcheck:
      check-type-assertions: true
      check-blank: true

formatters:
  enable:
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/patrickdappollonio/mockingjay
